<?php

/**
 * See LICENSE.md file for further details.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use LilaElephant\Webtrees\Topola\Configuration;

/** @var Configuration $configuration */
/** @var string $title */
/** @var string $moduleName */
/** @var Individual $individual */
/** @var Tree $tree */
/** @var array $chartParams */
/** @var string $javascript */
/** @var string $ajaxUrl */

?>

<div id="page-topola">
    <h2 class="wt-page-title"><?= $title ?></h2>

    <iframe
        id="topolaFrame"
        style="width: 100%; height: 800px;"
        src="https://pewu.github.io/topola-viewer/#/view?indi=<?= $individual->xref(); ?>&utm_source=webtrees&embedded=true">
    </iframe>
</div>

<?php View::push('javascript'); ?>
<script>
    var GEDCOM_URL = '<?= $ajaxUrl; ?>';
</script>
<script src="<?= e($javascript) ?>"></script>
<?php View::endpush(); ?>
